version: "3.7"
services:
  studentdata:
    image: studentdata:latest
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - gotest
  abcschool:
    image: abcschool:latest
    expose:
      - 9091
    ports:
      - 9091:9091
    networks:
      - gotest
networks:
  gotest:
    driver: bridge
    name: gotest